# Generated by Django 3.1.4 on 2020-12-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_group_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
    ]
